### ISSUE TITLE
How can I contribute to this project? 

### ISSUE THREAD

**Issue by foragerDev** [KamalDevelopers/GevOS#2]
Hi, I am new to Open source, so I am trying to contribute to open source projects, I found your project interesting. I wanna contribute to it? How can I?

**Comment by Edersteiner** [comment]
If you want to contribute, you could start with trying to build GevOS by following the guide on our wiki. And then, If you believe that you have made good changes or maybe a good new feature, you should make a pull request. We will then review that pull request and if we like it, we will accept it and merge it. Otherwise, we will decline it and post a comment with feedback or reasoning why we declined your change.

**Comment by foragerDev** [comment]
OK, for now I am not able to Make PR. It says I have No permission.

**Comment by Edersteiner** [comment]
That's weird. We have had people do pull requests before.

**Comment by foragerDev** [comment]
I have not idea, why is it so.

![image](https://user-images.githubusercontent.com/32019091/105406333-171e5380-5c4e-11eb-9cff-02da76d8a033.png)

**Comment by Edersteiner** [comment]
The way we have done it before is through GitHub and not just plain git. You need to have a fork of GevOS on your GitHub profile and then create a pull request in GitHub.

**Comment by foragerDev** [comment]
alright. Got it.
