### ISSUE TITLE
Backspace is not working in terminal

### ISSUE THREAD

**Issue by foragerDev** [KamalDevelopers/GevOS#4]
I am working on it.

**Comment by Edersteiner** [comment]
This is known for quite some time, we don't focus that much on GUI so it just hasn't been fixed.

**Comment by DevGev** [comment]
The terminal is not a huge priority right now. It is mostly a "preview" of the GUI library which also has to be updated in the future. Our goal is to make the terminal code a stand-alone application which will run as a separate elf application process.

**Comment by Edersteiner** [comment]
Yeah, A rewrite of the GUI is planned. So LibGUI development will not mean much in the future.

**Comment by foragerDev** [comment]
All right, can you please let me know where to work on, like something very basic so that I can get familiar with code base, or if you can make issues for me so that  and assign me, I will do that after my work hours, are you okay with it?

**Comment by DevGev** [comment]
Fantastic to see you engaging in our project! If you want to make small contributions and fixes I would recommend you to start working on expanding our LibC (the GevOS standard library). You could look at references of the current C/C++ standard library to get some ideas for functions to implement. A good reference point would be [cppreference](https://en.cppreference.com/w/cpp/header). We also encourage you to start using Clang formatting when making contributions to this project since it helps us keep the code clean and consistent. For more information read the [wiki](https://github.com/KamalDevelopers/GevOS/wiki/Building-GevOS).

**Comment by foragerDev** [comment]
I am always interested  and wonder How Operating systems are developed basically that was my motivation to get degree in Software Engineering , I guess it would be great way to learn how OS systems works and build (I have theoretical knowledge about it), I am not just eager to make small contributions but I am looking forward to implement some major components of OS features, I am just looking forward for a way to get started. I know C++ fair enough(I know its too much exaggeration  ;) ) , but I have never been able to use somewhere in the real world. If you guys guide yeah sure, I am eager to learn more from you buy doing something I am interested in.
