### ISSUE TITLE
Inconsistent code style

### ISSUE THREAD

**Issue by foragerDev** [KamalDevelopers/GevOS#8]
The code is not following any particular standard, somewhere it has PascalCase, somewhere it has camelCase, some where snake_case. It has be consistent.

**Comment by DevGev** [comment]
The casing we use depends on where in the code the function is located and in what context the function exists.
Functions within classes should be PascalCased. While stand-alone functions are snake_cased. We use different cases to specify the context of our functions, which is not something unique about GevOS as you will see this type of formatting in many other OS projects.

**Comment by foragerDev** [comment]
Alright, I know that, can you please tell me why here is the difference? 
![image](https://user-images.githubusercontent.com/32019091/105755938-c8cec480-5f6d-11eb-8f50-645e6743fe29.png)

**Comment by DevGev** [comment]
That is a mistake and should in fact not be cased like that. Some inconsistencies like this may exist in some older parts of the kernel, such as the mouse driver which rarely gets updated. The reason for this is because some of the code is derived from my older OS project. If you see anything that is clearly miss cased  you can freely change it to the right casing.

**Comment by foragerDev** [comment]
yeah sure, I am fully into this project now, and I am planing something big.
